name: deploy-shell

on:
  push:
    branches:
      - master
    paths:
#      - 'shell/**'
#      - './package.json'
#      - './package-lock.json'
#      - './angular.json'
#      - './tsconfig.json'
#      - '.github/workflows/shell.yml'

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd shell && npm ci
      - run: export HOST=${{ secrets.HOST }} && cd shell && npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET_NAME }} --recursive --dryrun --exclude "*" --include "shell/latest/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-3"

      - run: aws s3 sync shell/dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/shell/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-3"

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/shell/latest/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-3"